name: Spring Boot API CI Workflow

on:
  pull_request:
    branches: [rest-api]
    paths:
      - "authexample/**"
      - "!authexample/README.md"
      - "!authexample/docs/**"
      - "!authexample/env_examples/**"
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_call:


defaults:
  run:
    working-directory: ./authexample

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.9.5

      - name: Install maven dependencies
        run: mvn install -DskipTests

      - name: Set up node for firebase emulator
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'

      - name: Install firebase emulator
        run: npm install -g firebase-tools
      
      - name: Run tests
        run: firebase emulators:exec --only auth --project $FIREBASE_TEST_PROJECT 'mvn test > test_logs.txt'
        env:
          FIREBASE_CREDENTIALS_CONTENT: ${{ secrets.FIREBASE_CREDENTIALS_CONTENT }}
          FIREBASE_TEST_PROJECT: ${{ vars.FIREBASE_TEST_PROJECT }}

      - name: Generate test report
        if: always()
        run: |
          mvn surefire-report:report-only
          mvn site -DgenerateReports=false

      - name: Zip test logs and report
        if: always()
        run: |
          zip -r full-test-report.zip target/site target/surefire-reports
          zip full-test-report.zip test_logs.txt         

      - name: Upload test logs and report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs-and-report
          path: ./authexample/full-test-report.zip
          if-no-files-found: error
          retention-days: 1